src/client/api/__tests__/courses.test.ts
src/client/api/courses.ts
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/Courses/__tests__/CoursesPage.test.tsx
src/client/components/pages/Courses/__tests__/tableFields.test.tsx
src/client/components/pages/Courses/tableFields.tsx
src/common/__tests__/data/courseInstances.ts
src/server/courseInstance/__tests__/courseInstance.controller.test.ts
src/server/courseInstance/courseInstance.controller.ts

This primarily fixes the bug where meetings without assigned rooms would break the entire front end. Along the way I found a related bug that similarly breaks the front end when no data is returned from the server, and I fixes that by changed the response from the getInstances endpoint to return only a single-level array of courses, instead of a two-dimensional array of courses. 
(The two-dimensional array was originally used so we could fetch multiple academic years' worth of data in the background, but that doesn't seem like a hard requirement anymore, and switching to the single array makes this second bug much easier to fix).
to change)
Fixes #297

Fix rendering bugs with bad data

---

src/common/dto/room/RoomResponse.dto.ts

The server will return an array of room responses. For each room, it will include the room id, campus, name (building and room number concatenated), capacity, and an array of course titles/non class meeting titles that are taking place during the time requested in the request params.
to change)
Fixes #312

RoomResponse DTO

---

src/client/components/pages/Courses/CourseInstanceTable.tsx
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/Courses/MeetingModal.tsx
src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
src/client/components/pages/Courses/__tests__/tableFields.test.tsx
src/client/components/pages/Courses/tableFields.tsx
src/client/context/CoursesPageContext.ts
src/client/context/index.ts
src/common/__tests__/data/courseInstances.ts
tests/integration/client/courseInstance/meeting.test.tsx

This PR adds the skeleton of the room booking modal. It includes the modal header, body, and footer, and it sets the focus to the header and edit meeting button appropriately (On modal open, the header is focused. On modal close, the edit button that was originally clicked to open the modal is focused). 
to change)
Fixes #305

Room Booking Modal Furniture 

---

src/client/components/pages/Courses/MeetingModal.tsx

This PR updates the formatting of the meeting modal to have two sections, Meeting Scheduler and Room Availability, instead of three (originally there was a Faculty Notes section). I used flexbox in order to get the two divs to scroll independently instead of having the scrollbar on the entire modal body - I struggled to find a way to accomplish the independent scrolling of sections with CSS grid but am welcome to suggestions if CSS grid is the preference. Also, each section's headings are sticky so that when the user scrolls, the header is still visible.
Below are some screenshots of the two sections filled with sample content:
to change)
Fixes #305

Update Meeting Modal Formatting

---

src/server/migrations/1622033603597-AddDatabaseComments.ts

The "contact" column in the NonClassParent was renamed in an earlier migration on a separate branch, so we need to need to remove the lines that attempt to change it.
Since this PR edits an existing migration, I recommend dumping and rebuilding the entire database.
to change)
Fixes #___

Remove comment on "contact" column

---

src/client/components/general/typography/__tests__/CampusIcon.test.tsx
src/client/components/general/typography/__tests__/HiddenText.test.tsx
src/client/components/layout/__tests__/AppHeader.test.tsx
src/client/components/layout/__tests__/VerticalSpace.test.tsx
src/client/components/pages/Courses/__tests__/CourseInstanceTable.test.tsx
src/client/components/pages/Courses/__tests__/CourseModal.test.tsx
src/client/components/pages/Courses/__tests__/CoursesPage.test.tsx
src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
src/client/components/pages/Courses/__tests__/tableFields.test.tsx
src/client/components/pages/Faculty/__tests__/FacultyAbsenceModal.test.tsx
src/client/components/pages/Faculty/__tests__/FacultyModal.test.tsx
src/client/components/pages/Faculty/__tests__/FacultyTable.test.tsx
src/client/components/pages/Schedule/__tests__/SchedulePage.test.tsx
src/client/components/pages/Schedule/__tests__/ScheduleView.test.tsx
src/client/components/pages/__tests__/CourseAdmin.test.tsx
src/client/components/pages/__tests__/FacultyAdmin.test.tsx
src/client/components/pages/__tests__/MultiYearPlan.test.tsx
src/common/__tests__/utils/customRender.tsx
tests/integration/client/course/courseAdmin.test.tsx
tests/integration/client/courseInstance/meeting.test.tsx
tests/integration/client/faculty/faculty.test.tsx
tests/integration/client/faculty/facultyAdmin.test.tsx

Just grabbing a tech debt ticket off the backlog. This will improve the way that additional parameters are passed into to our customRender function by accepting an object with name properties as the second argument, instead of a function. It also provides defaults for those parameters, so that it's acceptable to just call `render(<Component />)` without needing to pass an unnecessary stub or empty function.
This required changing a lot of existing calls to `render()`, so I've removed entirely any `dispatchMessage` arguments that weren't being used, and switched to the property value shorthand (i.e. `{ dispatchMessage }` for those that are being used. I've tried to group like changes under the same commits for ease of review.
This is a pretty low priority change, so feel free to take your …

Improve additional parameter handling in customRender

---

src/client/components/pages/Courses/MeetingModal.tsx
src/client/components/pages/Courses/RoomSelection.tsx
src/client/components/pages/Courses/RoomSelectionTable.tsx
src/client/components/pages/Courses/__tests__/RoomSelectionTable.test.tsx
src/common/__tests__/data/index.ts
src/common/__tests__/data/locations.ts
src/server/location/location.service.ts
tests/integration/server/location/location.controller.test.ts

This implements the initial layout and minimal functionality of the Room Selection Table that appears in the right-hand side of the meeting booking modal. There is a default day and time hard-coded into the `MeetingModal` component, and when the `RoomSelection` renders it will autmatically request those rooms from the server, then render the list.
Note that the "Add" buttons are currently non-functional, and the "Availability" filter dropdown does not actually do any filtering. The "Add meeting time" prompt will appear if the list of rooms is empty and nothing is being requested, so to demo that at this stage you can change line 60 of `RoomSelection.tsx` to pass an empty array into the `RoomSelectionTable`:
```tsx
<RoomSelectionTable
roomList={[]}
addButtonHandler={roomHandler} …
```

Bootstrap Room Selection Table

---

src/client/components/pages/Courses/MeetingModal.tsx
src/client/components/pages/Courses/RoomSelection.tsx
src/client/components/pages/Courses/RoomSelectionTable.tsx
src/client/components/pages/Courses/__tests__/RoomSelectionTable.test.tsx
src/common/dto/room/RoomRequest.dto.ts
src/server/location/location.service.ts
tests/integration/server/location/location.controller.test.ts

This became slightly more complicated that initially expected, mainly because we needed to exclude the current `courseInstance`/`nonClassEvent` meeting from appearing in the list of meetings -- otherwise we wouldn't be able to change a room then change it back in the same editing session. This is better handled on the server side as part of the roomAvailability request, since we can exclude the instance based on its UUID, but that required some refactoring of the `LocationService#getRooms` method.
There were also some changes around setting the buttons to `disabled` when the room can't be added. A number of articles ([example][ex]) made the point that disabled buttons have some inherent accessibility/usability issues, and our existing `disabled` buttons in Mark One don't provide any …

Meeting Modal: Add button in Room Selection Table

---

src/client/api/__tests__/nonclassmeetings.test.ts
src/client/api/index.ts
src/client/api/nonClassMeeting.ts
src/client/components/layout/AppRouter.tsx
src/client/components/pages/Courses/tableFields.tsx
src/client/components/pages/NonClassMeetings/NonClassMeetingsPage.tsx
src/client/components/pages/NonClassMeetings/NonClassMeetingsTable.tsx
src/client/components/pages/NonClassMeetings/__tests__/NonClassMeetingsPage.test.tsx
src/client/components/pages/NonClassMeetings/__tests__/NonClassMeetingsTable.test.tsx
src/client/components/pages/index.ts
src/common/__tests__/data/index.ts
src/common/__tests__/data/nonClassEvents.ts
src/common/dto/nonClassMeetings/NonClassMeeting.dto.ts
src/server/migrations/1627061779480-RenameAcademicYearToCalendarYear.ts
src/server/nonClassEvent/NonClassEvent.view.entity.ts
src/server/nonClassEvent/NonClassParentView.entity.ts
src/server/nonClassEvent/__tests__/nonClassEvent.controller.test.ts
src/server/nonClassEvent/nonClassEvent.controller.ts
src/server/nonClassEvent/nonClassEvent.service.ts
tests/integration/server/nonclassevents/nonclassevent.service.test.ts

This PR implements the basic, bare-bones non class meetings table. None of the buttons are currently functional, there are no modals, no handlers etc. Just the display of the data from the API in the table.
I would like to draw attention to a couple of commits - namely the last two (0d2ec50bca8852864cb3fd95c327b736cef88274 & 38169b24002f5b1cad71c05393ef458ca5c5dead). The first of those two commits changes the way that the table is tested and uses `within` instead of  `getAllbyRole().filter` to pair down the search space of the `getAllBy()` function. This caused the test to timeout (and thus fail). When changing that, there was a logic error that I noticed before committing but purposefully left in so that I could deal with it in another commit and highlight another potential issue that I …

Add non class meetings table

---

src/common/dto/nonClassMeetings/CreateNonClassParent.dto.ts

This PR introduces the DTO representing the shape of the data being used to create a non-class parent on the server. Child data such as non-class events are not included in this DTO because those will be generated automatically by the server. Similarly meetings will be added on an as-needed basis by the user using the GUI, so those aren't sent over either.
to change)
Delivers the first piece of #389

Add CreateNonClassParent DTO

---

.mochainit.ts
.mocharc.js
tests/integration/client/course/courseAdmin.test.tsx
tests/integration/e2e/CoursesPage.test.tsx
tests/integration/server/course/course.entity.test.ts
tests/integration/server/course/course.service.test.ts
tests/integration/server/courseInstance/courseInstance.controller.test.ts
tests/integration/server/courseInstance/courseInstance.service.test.ts
tests/integration/server/faculty/faculty.service.test.ts
tests/integration/server/faculty/facultySchedule.test.ts
tests/integration/server/location/location.controller.test.ts
tests/integration/server/meeting/meeting.controller.test.ts
tests/integration/server/nonclassevents/nonclassevent.service.test.ts
tests/mocks/database/MockDB.ts
tests/mocks/database/population/__tests__/population.service.test.ts
tests/mocks/database/population/population.service.ts

After running up against yet another string of phantom test failures I decided it was worth trying to make some changes to the test setup. This PR rolls up a couple of small things that, hopefully, should resolve the deadlock issues we've occasionally seen:
1. Instead of running a fresh container for each test suite, we're just going to start a single container, which we can dump and repopulate before each test.
2. The container will not run if passing `--client` or `--server`, i.e., `npm run test -- --client`
3. The container can be skipped by changing the value of `MOCHA_NEEDS_DATABASE` when running the tests
4. The container now uses a random port in the 3xxxx range to avoid port conflicts
5. The container uses a unique name to avoid naming conflicts
6. The container only listens on …

Attempt to stabilize tests

---

package-lock.json
package.json
src/client/components/pages/Courses/InstructorModal.tsx
src/client/components/pages/Courses/__tests__/InstructorModal.test.tsx
src/client/components/pages/Courses/__tests__/tableFields.test.tsx
src/client/components/pages/Courses/tableFields.tsx
tests/integration/server/courseInstance/courseInstance.controller.test.ts

This creates the modal for editing the instructor list assigned to a course instance. At present, it just renders the list, in order, with nonfunctional delete and up/down buttons that will be wired up in future PRs.
Note that I haven't implemented anything related to the unsaved changes  yet, as there's no editing functionality with which to test it.
to change)
Fixes #376

Initial implementation of Instructor Modal

---

package-lock.json
package.json
src/client/api/faculty.ts
src/client/components/pages/Courses/InstructorModal.tsx
src/client/components/pages/Courses/__tests__/InstructorModal.test.tsx
src/server/faculty/faculty.controller.ts
src/server/faculty/faculty.service.ts
tests/integration/server/faculty/faculty.controller.test.ts
tests/integration/server/faculty/faculty.service.test.ts

This adds a `<Combobox>` input to the Instructor modal, from which new instructors can be assigned to a given course instance. Populating the list of available instructors required adding an additional API endpoint. This PR also adds the "confirm unsaved changes" functionality to the Instructor Modal, though we still haven't implemented the "Save" functionality, so I've held off on adding full end-to-end testing for it.
to change)
Fixes #375

Add Instructor functionality

---

src/common/dto/view/CreateView.dto.ts
src/common/dto/view/UpdateView.dto.ts
src/common/dto/view/ViewResponse.dto.ts

This PR delivers #432 and specs out the data shapes for the controller CRUD endpoints for custom view functionality on the course admin page
to change)
Fixes #432

Custom View DTOs

---

src/client/components/pages/Schedule/SchedulePage.tsx
src/client/components/pages/Schedule/__tests__/SchedulePage.test.tsx

This ticket was completed during a mob programming session.
to change)
Fixes #444

Update Schedule Table with current semester data

---

src/client/components/pages/Schedule/SchedulePage.tsx
src/client/components/pages/Schedule/__tests__/SchedulePage.test.tsx
src/common/__tests__/data/metadata.ts
src/common/utils/__tests__/util.test.tsx
src/common/utils/termHelperFunctions.ts
src/common/utils/util.ts

This ticket was completed during a mob programming session.
to change)
Fixes #445

Add semester schedule dropdown

---

src/client/components/pages/Courses/CourseInstanceTable.tsx
src/client/components/pages/Courses/CourseInstanceTableBody.tsx
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/Courses/InstructorModal.tsx
src/client/components/pages/Courses/MeetingModal.tsx
src/client/components/pages/Courses/__tests__/CourseInstanceTable.test.tsx
src/client/components/pages/Courses/__tests__/CoursesPage.test.tsx
src/client/components/pages/Courses/__tests__/InstructorModal.test.tsx
src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
src/client/components/pages/Courses/filters.d.ts
src/client/components/pages/Courses/tableFields.tsx
src/client/components/pages/MultiYearPlan.tsx
src/client/components/pages/__tests__/MultiYearPlan.test.tsx
src/client/components/pages/utils/__tests__/filterByInstructorValue.test.tsx
src/client/components/pages/utils/filterByInstructorValues.ts
tests/integration/e2e/CoursesPage.test.tsx

This PR adds the text filters for the Course Instance table, debouncing (`filters` state does not update if the user types additional keystrokes within 100ms), and performance enhancements for the filter fields.
While implementing the text filters, I found that typing in the text filter fields was incredibly slow, leading to a poor user experience. Each keystroke was taking more than a second to appear. Thus, I worked on some performance improvements in order to give the user a better experience in interacting with the text filters.
I found that with each keystroke, this was updating the `filters` state, which caused the table to re-render. These re-renders were causing a lot of delays in the UI. In order to solve this issue, I separated the table body component into a memoized component …

Add Course Instance Table Text Filters (with debouncing and performance improvements)

---

src/client/components/App.tsx
src/client/components/layout/Message.tsx
src/client/components/layout/__tests__/Message.test.tsx
src/client/components/pages/Courses/CourseInstanceTable.tsx
src/client/components/pages/Courses/CourseInstanceTableBody.tsx
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/Courses/InstructorModal.tsx
src/client/components/pages/Courses/MeetingModal.tsx
src/client/components/pages/Courses/__tests__/CourseInstanceTable.test.tsx
src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
src/client/components/pages/Courses/__tests__/tableFields.test.tsx
src/client/components/pages/Courses/tableFields.tsx
src/client/context/MessageContext.ts
src/common/__tests__/utils/customRender.tsx

This PR refactors a bunch of implementation details of the `CoursesPage`/`CourseInstanceTable` to improve performance by minimizing the number full re-renders that are triggered by prop/state changes. Under the previous implementation, the entire UI would freeze for ~1.5 seconds whenever a modal opened or closed, and whenever an AppMessage was dispatched/cleared. These changes have removed the AppMessage delays entirely, as well as the modal open delays. There's still a 1-2s delay when saving a Modal (since the complete course list needs to update) but we at least have the loading spinner in place so it's at least clear that things are happening.
I strongly suggest reading through the git commit messages, as I've tried to go into detail about why the different changes were implemented and …

Improve Course Instance Table performance

---

package-lock.json
package.json
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/utils/downloadAttachment.ts
src/common/constants/index.ts
src/server/app.module.ts
src/server/report/__tests__/utils.test.ts
src/server/report/report.controller.ts
src/server/report/report.module.ts
src/server/report/report.service.ts
src/server/report/utils.ts
tests/integration/server/auth/auth.test.ts
tests/integration/server/report/report.test.ts

This implements the initial version of our Course Report in xlsx format. As specified in #474, this version does not include any additional formatting or styling, and simply presents each course as one row, with columns for course-wide properties as well as individual semester properties. We're defaulting to starting with the current academic Year and extending to cover all of the years in the database.
This PR adds one additional dependency, `exceljs`, so it will require an `npm install` to run the code locally.
The server implementation uses the streaming I/O interface in exceljs to write the Excel workbook directly to the express response stream. The Nest docs do mention a `StreamableFile` class for handling streams like this, but that was added in a new major version of Nest and I …

Initial courses excel report

---

src/client/api/index.ts
src/client/api/reports.ts
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/Courses/ReportDownloadModal.tsx
src/client/components/pages/Courses/__tests__/ReportDownloadModal.test.tsx
src/client/components/pages/utils/downloadAttachment.ts
src/server/report/report.controller.ts
tests/integration/server/report/report.test.ts

This replaces the existing "Download Course Report" button behavior. Now, Instead of immediately downloading a report for the default date range (covering from the current academic year to the last available semester) it will now open a model with two dropdowns to select the year range. The default will remain the default, and there is also code to prevent users from selecting invalid ranges; if someone attempts to choose a start year after the end year, the end year will update to that same year (and vice versa) to provide a single-year report.
The majority of the changes are on the client side; there are a few validation changes to the controller method that gets the report, but the actual report generation code is unchanged.
I did run into a bit of a hurdle with testing the client …

Allow custom report date ranges

---

src/client/api/httpStatus.ts
src/client/api/index.ts
src/client/components/pages/Courses/NotesModal.tsx
tests/integration/client/courseInstance/notesModal.test.tsx

This PR Fixes an issue where a server-side error thrown by the server (be that a validation error or general 500) can break the modal update code but with no indication to the user as to the nature of the problem. The fix for this is to concat all the validation errors into a single string and show them beneath the modal or(in the case of a general 500 error) just show a generic error message below the text area.
Since this code is ~~shamelessly ripped from~~ very similar to [the code for showing server-side errors in the enrollment modal](https://github.com/seas-computing/course-planner/blob/develop/src/client/components/pages/Courses/EnrollmentModal.tsx#L274-L293) I do just want to call out one key difference which is that unlike the enrollment modal, no effort is being made here to …

Show server errors in edit notes modal

---

.github/workflows/01-test-suite.yml
.github/workflows/03-version.yml
.github/workflows/04-documentation.yml
.github/workflows/05-publish.yml
package-lock.json
package.json
src/client/components/pages/Courses/EnrollmentModal.tsx
src/client/components/pages/Courses/__tests__/EnrollmentModal.test.tsx
src/server/semester/semester.service.ts

This release fixes three bugs:
- Prevents errors in the `addAcademicYear` process from blocking app startup (#520)
- Removes dependency on `@nestjs` package that was breaking the client build (#518)
- Adds `concurrency` field to workflows to avoid race conditions and test timeouts (#522)

Merge to main

---

package-lock.json
package.json
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/Faculty/FacultyPage.tsx
src/client/components/pages/Faculty/__tests__/FacultyPage.test.tsx
src/client/components/pages/utils/academicYearOptions.ts
tests/integration/client/faculty/faculty.test.tsx

This PR adds the academic year dropdown for the Faculty page. The logic for creating the dropdown options is the same as the academic year dropdown on the Courses page, so it was extracted to its own function and is called for both the courses and faculty academic year dropdowns. I also used the `useStoredState` hook so that the same option is selected if the user navigates away from and returns to the Faculty tab. 
to change)
Fixes #532

Faculty Page Academic Year Dropdown

---

src/client/components/pages/Schedule/ScheduleView.tsx
src/client/components/pages/Schedule/blocks/SessionBlock.tsx

This started as a fairly straightforward style update, but got a little more complicated thanks the weirdness of absolute and relative positioning. The final version differs in implementation from what @Vittorio2015 sketched out in #526, but achieves essentially the same effect.
I also managed to find a way to add up/down indicators to show when there's more content in either direction:
> View of Wednesday afternoon in Spring 2020
Since those indicators are defined in CSS they should affect the actual DOM output parsed by screen readers. The downside, though, is that there isn't a great way to add tests for the indicators in our current system (though I'm certainly open to suggestions).
to change)
Fixes #526

Make schedule blocks scrollable

---

.npmrc
Dockerfile
package-lock.json
package.json

This Pull Request should resolve the issues with building the course-planner container on ARM-based systems (e.g. Apple's M1 Macs). Chris provided some details on this in #455, but essentially the problem is that the `node-canvas` package being pulled in as an option dependency of `jsdom` needs to install a binary package, `cairo`, that doesn't have ARM builds available.
The current solution recommended by the project is to use the `--build-from-source` flag to `npm install`, which is _fine_ but introduces some additional overhead for a package that we're not even really using. Given that, it makes more sense to just omit the "optional" packages altogether and proceed on the assumption that any optional packages we do need should be installed explicitly.
This also lets us avoid the other …

Omit Optional dependencies by default

---

src/client/api/__tests__/location.test.ts
src/client/api/rooms.ts
src/client/components/pages/RoomAdmin/CreateRoomModal.tsx
src/client/components/pages/RoomAdmin/RoomAdmin.tsx
src/client/components/pages/RoomAdmin/__tests__/RoomAdminTable.test.tsx
src/client/context/MetadataContext.ts
src/common/__tests__/data/locations.ts
src/common/dto/room/CreateRoomRequest.dto.ts
src/server/location/__tests__/location.service.test.ts
src/server/location/building.entity.ts
src/server/location/location.controller.ts
src/server/location/location.service.ts
src/server/location/room.entity.ts
tests/integration/client/room/roomAdmin.test.tsx
tests/integration/e2e/RoomAdmin.test.tsx
tests/integration/server/location/location.controller.test.ts
tests/integration/server/location/location.service.test.ts

This PR adds the Create Room modal, which allows users to create new rooms and buildings. The following rules apply to this modal:
- All of the fields in the Create Room modal are required, and errors should show up for each empty field when the user clicks submit.
- If the user tries to add a duplicate room, an error should be thrown indicating the room already exists.
- The capacity field must be a number.
- Changing the campus dropdown triggers the "Select existing building" dropdown to load data for the campus selected. 
- If the user tries to add an existing building in the "New Building" field, an error should be thrown that redirects the user to select the building in the dropdown instead.
- If the user tries to specify a building that exists on a different campus, they should get …

Add Create Room modal

---

src/client/components/pages/Faculty/FacultyAbsenceModal.tsx
src/client/components/pages/Faculty/FacultyPage.tsx
tests/integration/client/faculty/faculty.test.tsx

Update faculty absence page to update local state instead of reloading the page

---

src/client/components/pages/Faculty/FacultyScheduleTable.tsx
src/client/components/pages/Faculty/__tests__/FacultyPage.test.tsx
src/client/components/pages/Faculty/__tests__/FacultyTable.test.tsx
src/common/__tests__/data/faculty.ts

This PR adds filters for the Faculty table including the area, first and last name, category, and absence filters.
to change)
Fixes #582

Add Faculty Table Filters

---

src/client/components/pages/RoomSchedule/RoomSchedule.tsx

This styled component adds padding and a minimum width to prevent the component from stretching all the way to the end of the page horizontally.
to change)
Fixes #584

Update Room Schedule Layout

---

.github/workflows/05-publish.yml

This added step will check out the latest version of our code, as determined in the pre-publish stage. We need this because the checkout action will, by default, run on the "main" branch, and we want to be sure that we're building off of whatever code was just merged by using the incremented version tag.
Note that we're building both the `_QA` and `_PROD` static bundles off of the same code, but parsing different environment variable to set, among other things, the client and server URLs. This is different from our docker images, where the `:qa` and `:stable` tags track the develop and main branches, respectively. This is kind of confusing and may change in the future, but for now I suggest we leave it as is.
to change)
Fixes #___

Checkout version before building

---

package-lock.json
package.json
src/client/components/general/flex/RightMenu.tsx
src/client/components/general/flex/index.ts
src/client/components/pages/Courses/CoursesPage.tsx
src/client/components/pages/Courses/MeetingModal.tsx
src/client/components/pages/Courses/__tests__/CoursesPage.test.tsx
src/client/components/pages/Courses/tableFields.tsx
src/client/components/pages/Faculty/FacultyPage.tsx
src/client/components/pages/Faculty/__tests__/FacultyPage.test.tsx
src/client/components/pages/RoomSchedule/RoomSchedule.tsx
src/server/metadata/metadata.controller.ts

- Update Placeholder Text in Courses Table (fixes #599)
- Update placement of Academic Year Dropdowns (Fixes #597)
- Remove authentication from `/metadata` endpoint (Fixes #608)
- Move Loading indicator into `MeetingModal` body (Fixes #595)

Release v0.11.0

---

src/client/components/layout/AppHeader.tsx
src/client/components/layout/AppRouter.tsx
src/client/components/layout/__tests__/AppHeader.test.tsx
tests/integration/e2e/AppRouter.test.tsx

Hides the room schedule (for the time being) until we fix an API bug that throws a 401 for this page. 
to change)
Fixes #610

Hide room schedule on info page. 

---

package-lock.json
package.json
src/client/components/layout/AppHeader.tsx
src/client/components/layout/AppRouter.tsx
src/client/components/layout/__tests__/AppHeader.test.tsx
src/client/components/pages/Faculty/FacultyScheduleTable.tsx
src/client/components/pages/FacultyAdmin.tsx
src/client/components/pages/Schedule/ScheduleView.tsx
tests/integration/e2e/AppRouter.test.tsx

- Faculty, Faculty Admin: Make alignment of "Area" column consistent (fixes #600)
- Schedule: Show a regular cursor over inactive buttons (fixes #601)
- Room Schedule: Hide page on info.seas site (fixes #610)

Release v0.12.0

---

package-lock.json
package.json
src/client/api/__tests__/courses.test.ts
src/client/components/pages/Courses/__tests__/CourseModal.test.tsx
src/common/__tests__/data/courses.ts
src/server/course/__tests__/course.controller.test.ts
src/server/course/__tests__/course.service.test.ts
src/server/course/course.service.ts
src/server/courseInstance/courseInstance.service.ts
tests/integration/server/course/course.controller.test.ts
tests/integration/server/course/course.service.test.ts
tests/integration/server/courseInstance/courseInstance.service.test.ts

- 4 Year Plan, Course Admin: Sort courses by prefix/integer/alphabetical (fixes #616)
- Mark-one: Adjust color contrast on error messages (Fixes #598)
- Mark-one: Make padding consistent across rows (Fixes #602)
- Mark-one: Add aria-selected to Tabs (Fixes #247)

release v0.13.0

---

package-lock.json
package.json
src/client/components/pages/Faculty/FacultyPage.tsx
src/client/components/pages/utils/absenceToVariant.ts
src/common/constants/absenceType.ts
src/server/faculty/__tests__/faculty.controller.test.ts
src/server/faculty/__tests__/facultySchedule.controller.test.ts
src/server/faculty/faculty.controller.ts

- Create a blank absence for every semester in the database when creating new Faculty (Fixes #620)
- Prevent missing absences breaking the client page (Fixes #619)

Release v0.14.0
