seas-computing/course-planner

- src/client/components/layout/__tests__/AppRouter.test.tsx
- src/client/components/pages/CourseAdmin.tsx
- src/client/components/pages/__tests__/CourseAdmin.test.tsx
- src/client/context/MetadataContext.ts
This PR updates the area filter dropdown in the Course Admin tab to use `areas` from the `metadata`. The column header was originally "Course Prefix," but Jonathan Seitz agreed that we could change the column header name to "Area."
to change)
Fixes #269
> Fix Course Admin Area Filter Dropdown Values

- package-lock.json
- package.json
- src/client/components/pages/Courses/CourseModal.tsx
- src/client/components/pages/FacultyModal.tsx
This also adds a label to each of the forms. The prop hideError was added to the Undergraduate checkbox in the Course Modal form, because this checkbox may be left unchecked and the undergraduate field would never produce an error message.
to change)
Fixes #274
> Replace html form element with Mark-One Form component for CourseModal and FacultyModal forms

- src/client/components/pages/Faculty/FacultyScheduleTable.tsx
- src/client/components/pages/utils/__tests__/absenceToVariant.test.tsx
- src/client/components/pages/utils/absenceToVariant.ts
- src/common/__tests__/data/absence.ts
This PR applies the cell highlighting capability that was added in `mark-one` through [this TableCell Text Styling PR.](https://github.com/seas-computing/mark-one/pull/94). We decided on the styling through [ticket 300](https://github.com/seas-computing/course-planner/issues/300) taking color contrast into consideration. "Parental Leave" and "Research Leave" absences have the `negative text` color, and "No Longer Active" absences will have the `medium text` color - these three absence types will also have a bold font weight.
to change)
Fixes #300
> Apply Cell Highlighting - Faculty Absences

- src/client/components/pages/Courses/MeetingModal.tsx
- src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
- src/client/components/pages/utils/__tests__/instructorDisplayNameToFirstLast.test.tsx
- src/client/components/pages/utils/instructorDisplayNameToFirstLast.ts
- src/common/__tests__/data/courseInstances.ts
- src/common/dto/courses/CourseInstanceResponse.ts
- src/server/faculty/FacultyListingView.entity.ts
- src/server/migrations/1614877212117-AddFacultyNotes.ts
- tests/integration/server/courseInstance/courseInstance.service.test.ts
- tests/mocks/database/population/data/faculty.ts
- tests/mocks/database/population/data/index.ts
- tests/mocks/database/population/faculty.population.ts
This PR includes a migration that added the faculty notes to the FacultyListingView, so that these notes could be referenced within the meeting modal. When a faculty member does not have associated notes, we decided to put the italicized text, "No Notes", in place of notes. Otherwise, the faculty's associated notes are displayed.
to change)
Fixes #306
> Meeting Modal - Add Faculty Notes

- src/server/course/course.entity.ts
- src/server/location/RoomBookingInfoView.entity.ts
- src/server/migrations/1617223382839-EditNonClassProperties.ts
- src/server/nonClassEvent/nonclassevent.entity.ts
- src/server/nonClassParent/nonclassparent.entity.ts
This PR removes the `title` property from the `NonClassEvent` entity and the `course id` from the `NonClassParent`, as `NonClassParent` does not need to be tied to a course.
The `RoomBookingInfoView` was also updated so that the `title` displayed is from the `NonClassParent` rather than the `NonClassEvent,` since `title` is being removed from `NonClassEvent.`
A migration was generated for these changes.
to change)
Fixes #322
> Update NonClassParent and NonClassEvent Entities

- src/server/nonClassEvent/nonclassevent.entity.ts
- src/server/nonClassParent/nonclassparent.entity.ts
When creating `NonClassEvent`s in the course planner ETL, the `NonClassEvent` is not tied to a `NonClassParent` or a `Meeting`, presumably because the `cascade` property hasn't been set in these two `OneToMany` relationships in `NonClassEvent` and `NonClassParent`.
to change)
Fixes #322
> Add cascade property for Non Class entities

- src/client/components/pages/Courses/MeetingModal.tsx
- src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
- src/common/__tests__/data/courseInstances.ts
This PR fixes a bug in which there is no note displayed under an individual faculty member in the meeting modal when faculty `notes` is `null.`. This was occurring because the previous code was only checking whether `notes` was equal (`===`) to an empty string and not considering the case when `notes` is equal to `null.` The fix makes it so that if `notes` is equal to `null`, the text 'No Notes' will be displayed under the faculty member.
to change)
Fixes #331
> Fix Display of Faculty Notes when 'notes' is null - Meeting Modal

- src/server/courseInstance/ScheduleEntryView.entity.ts
This Should fix the issue where new migrations try to re-create the Schedule Entry View.
Previously I had changed the ScheduleEntryView definition so that it would no longer depend on the Room Listing View. In doing so I had introduced a bug by using "c" as the identifier for campus, when that was already being used for "course". While fixing that, I must have made some kind of merge/rebase error that kept "c" in the view definition, but changed it in the migration. So TypeORM keeps seeing that difference and trying to generate a new migration that replaces "c".
to change)
Fixes #___
> Fix table alias in expression

- src/server/migrations/1622033603597-AddDatabaseComments.ts
After a TypeORM update, comments are being added to existing columns generating a lot of extra noise in unrelated migrations. To  avoid this, let's just create all the comments in a single, one-off migration.
to change)
Fixes #___
> Add comments to database columns

- src/server/migrations/1622034068694-RestoreParentID.ts
There were two earlier migrations that both changed the RoomBookingInfoView, and since views are always dropped and recreated only the later migration persisted. This migration restores the changes from the earlier migration on top of the later migration, leaving us with only the combined view definition.
Relevant earlier migrations are:
- 1616098074342-RoomBookingInfoView.ts
- 1617223382839-EditNonClassProperties.ts
to change)
Fixes #___
> Restore Parent Id in View

- src/server/course/course.entity.ts
- src/server/migrations/1623944858236-SplitCourseNumber.ts
- tests/integration/server/course/course.entity.test.ts
This PR adds two additional fields to our `Course` entity, `numberInteger` and `numberAlphabetical`, These will make sorting courses much more straightforward, since we'll be ensure that, for example, "CS 50" is sorted before "CS 109a". 
This also implements an event listener on the `@BeforeInsert` and `@BeforeUpdate` events that will parse the `number` string and populate those fields automatically, so that none of our other code needs to change as a result of this.
to change)
Fixes #178
> Parse course.number into integer and alphabetical portions

- src/client/components/pages/Courses/RoomSelection.tsx
- src/client/components/pages/Courses/RoomSelectionTable.tsx
- src/client/components/pages/Courses/__tests__/RoomSelection.test.tsx
- src/client/components/pages/Courses/__tests__/RoomSelectionTable.test.tsx
- src/common/__tests__/data/locations.ts
This adds actual functionality to the availability dropdown in the room table header. Also does some minor refactoring to better isolate some of the state that was previously shared between the two components.
Per discussions with the team, there is no longer an `FAS` option in the dropdown, and rooms owned by FAS will be treated the same as other rooms re: availability. There is a slight change in how their availability column will be displayed: If the FAS room has any SEAS meetings booked already it will show as "No ([meetingName, ...])", but if there are not SEAS meetings booked it will show "Check FAS Availability"
to change)
Fixes #354
> Implement Availability Filtering

- src/client/components/pages/Courses/MeetingModal.tsx
- src/client/components/pages/Courses/MeetingTimesList.tsx
- src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
This PR adds functionality for the delete buttons for the meeting times in the room booking modal. The `removeMeeting` handler updates the state of all meetings, which lives in the `MeetingModal.` This handler is passed down to the `MeetingTimesList` component.
The tests check that the appropriate meeting is deleted regardless of whether the user is creating or editing meetings and whether the user is deleting the meeting currently being edited, a previously existing meeting, or a newly added meeting. 
to change)
Fixes #318
> Delete Meeting Time - Room Booking Modal (client)

- src/client/components/pages/Courses/MeetingTimesList.tsx
- src/client/components/pages/Courses/__tests__/MeetingModal.test.tsx
This PR adds a remove room icon next to the room (if there is one selected) for the meeting that is currently being edited. If there is no room selected, a remove room icon does not appear. When the remove room icon is clicked, the room is removed and the room availability table is cleared in case it was open so that it doesn't show the old status of availability. 
to change)
Fixes #352
> Meeting Modal: Remove Room

- src/server/migrations/1627061779480-RenameAcademicYearToCalendarYear.ts
This PR removes the lines of the RenameAcademicYearToCalendarYear migration that drops the `ScheduleBlockView.` This view is needed for the Schedule tab of Course Planner. 
This view is needed for the Schedule tab of Course Planner.
to change)
Fixes #391
> Update RenameAcademicYearToCalendarYear migration to revert drop of ScheduleBlockView

- package-lock.json
- package.json
- src/client/components/App.tsx
- src/client/components/layout/Message.tsx
- src/client/components/layout/__tests__/Message.test.tsx
- src/client/components/pages/CourseAdmin.tsx
- src/client/components/pages/Faculty/FacultyAbsenceModal.tsx
- src/client/components/pages/FacultyAdmin.tsx
- src/client/components/pages/utils/__tests__/messageHelperFunctions.test.tsx
- src/client/components/pages/utils/messageHelperFunctions.ts
- src/common/__tests__/utils/customRender.tsx
- tests/integration/client/faculty/faculty.test.tsx
- tests/integration/e2e/CourseAdmin.test.tsx
- tests/integration/e2e/FacultyAdmin.test.tsx
This PR adds success messages that were missing on successful save and applies the `Mark One` `GlobalMessage` component to all success messages. Tests were also added for the new success messages to make sure they were rendering properly at the right time. In order to check the content of the messages, `renderWithMessaging` was added, and it includes the `Message` component (the current `customRender` does not include the `Message` component).
to change)
Fixes #422
> Add success messages and apply GlobalMessage component

- src/client/components/pages/Courses/CoursesPage.tsx
- tests/integration/client/courseInstance/viewselector.test.tsx
> Retrieve column values from state object

- src/client/components/pages/Courses/CoursesPage.tsx
- src/client/components/pages/Courses/__tests__/CoursesPage.test.tsx
This adds a dropdown above the the course instance allowing users to select a different pair of semesters (i.e. academic year) for display in the table. 
The initial value is based on the `currentAcademicYear` value in the metadata, and the list of semesters to be displayed is generated from the complete list of semesters also present in the metadata -- treating the calendar year of each `SPRING` semester as the academic year, then formatting the appropriate fall/spring value into a string, (e.g. turning `SPRING 2022` into "Fall 2021 - Spring 2022").
There's also a minor change to where the Loading Spinner appears: Now it only replaces the `CourseInstanceTable`, so that the academic year selector remains visible while the new semester data is populating. 
to change)
Fixes #451
> Implement Academic Year navigation in Course Instance Table

- src/client/components/general/flex/MenuFlex.tsx
- src/client/components/general/flex/index.ts
- src/client/components/pages/Courses/CoursesPage.tsx
- src/client/components/pages/Courses/__tests__/CoursesPage.test.tsx
- src/common/__tests__/data/courseInstances.ts
This PR adds a checkbox filter for the `retired` field and replaces the hard coded `showRetired` value with a state value that changes as you interact with the checkbox. By default, the field is unchecked, meaning that retired courses are not shown initially.
I also added a `MenuFlex` component (not sure if the naming of this component is the best) used to add space between each of the options above the Course Instance table. As more items are added within `MenuFlex`, this component should continue to space each of those items evenly. 
to change)
Fixes #450
> Add Show Retired Checkbox Filter

- src/server/semester/semester.module.ts
- src/server/semester/semester.service.ts
- tests/integration/server/faculty/faculty.controller.test.ts
- tests/integration/server/semester/semester.service.test.ts
This is a quick fix for some tests that started failing on June 1, as our testModules started trying to add years that couldn't be created. It adds an additional check to make sure that we're running in Production before attempting to call the function, which resolved most of the failing tests. (The Faculty API test suite was forcing the `NODE_ENV` to be production, but that seemed unnecessary and removing it fixed the failures without breaking anything else.)
to change)
> Add new year in production only

- package-lock.json
- package.json
- src/client/components/general/typography/HiddenText.tsx
- src/client/components/pages/Schedule/SchedulePage.tsx
- src/client/components/pages/Schedule/ScheduleView.tsx
- src/client/components/pages/Schedule/__tests__/ScheduleView.test.tsx
- src/client/components/pages/Schedule/blocks/CourseListingButton.tsx
- src/client/components/pages/Schedule/blocks/WeekBlock.tsx
- src/client/components/pages/Schedule/blocks/index.ts
- src/common/__tests__/data/schedule.ts
- src/common/dto/schedule/schedule.dto.ts
This puts in the place the initial Popover effect on the schedule page, displaying a single information box next to a course number when clicking on it. A future ticket (#504) will add boxes next to every meeting of the same course in the schedule.
This will still need an accessibility review, but the current implementation:
1. Hides the button containing the course number and the popover from screen readers
2. Replicates the popover text inside of a "HiddenText" block that should replace the entire content of the list item.
This should give screen readers access to the same information contained in the popover, without needing to go through the click-to-display process.
to change)
Fixes #503
> Add meeting info popups to Schedule

- src/common/dto/courses/UpdateCourse.dto.ts
- tests/integration/server/course/course.controller.test.ts
This PR makes the `termPattern` field of the `UpdateCourse` DTO. The requirement of this field to not be null was causing erroneous validation errors to be thrown when trying to update course instances that had a null value for this field. This null value was originating in data imported from the old course planner system indicating null values are a perfectly acceptable value for this field. The database schema also allows for this, so the API disallowing null values here is likely an oversight(especially since this value isn't actually used by the app).
to change)
Fixes #499
> Make termPattern optional

- src/client/components/pages/Courses/EnrollmentModal.tsx
- src/client/components/pages/Courses/__tests__/EnrollmentModal.test.tsx
HTTP status codes were re-defined in api/ for client-side code rather than importing the enum defined in `@nestjs/core`. This is because importing `@nestjs/core` in client-side code caused build failures.
to change)
Fixes #517
> Import HTTP status codes from api/

- src/server/semester/semester.service.ts
Originally without the `await` preceding the call of `addAcademicYear` in `onApplicationBootstrap`, the error thrown in `addAcademicYear` was not being handled properly. Adding this `await` makes it so that we can catch the error and log it appropriately.
The following error was getting thrown as a unhandled promise instead of getting logged: ```UnhandledPromiseRejectionWarning: Error: Cannot create requested academic year until preceding academic year is created."```
to change)
Fixes #519
> Fix addAcademicYear Unhandled Promise Rejection Warning

- .github/workflows/01-test-suite.yml
- .github/workflows/03-version.yml
- .github/workflows/04-documentation.yml
- .github/workflows/05-publish.yml
The [concurrency][1] field prevents multiple instances of the same
workflow (or any two workflows with the same concurrency value) from
running at the same time. It will also cancel/replace pending workflows
when the new one attempts to run. That could put us in an edge case
where a PR test run could be skipped, but I think a skipped test run is
probably better in the long run than a failed test run. In either case,
this should not affect any active workflows.
I've added individual concurrency groups for the test, versioning,
documentation, and publication stages. The PR check workflow is simple
enough that it shouldn't have any problems running concurrently, but we
can always revisit in the future.
[1]:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions# …
> Avoid concurrent workflows

- src/client/components/layout/InstructionalTextBox.tsx
- src/client/components/pages/MultiYearPlan.tsx
- src/client/components/pages/__tests__/MultiYearPlan.test.tsx
- src/client/components/pages/utils/getHostname.ts
This PR adds instructional text from the current course planner to the multi year plan tab when the user is visiting from info.seas. The planning.seas page will continue not displaying this instructional text.
The description from PR #472 outlines how to see the public-facing (info.seas.harvard.edu) and private-facing (planning.seas.harvard.edu) versions of course planner to see this change. 
to change)
Fixes #471
> Add Instructional Text to Multi Year Plan tab for info.seas only

- src/client/components/pages/Schedule/ScheduleView.tsx
- src/client/components/pages/Schedule/blocks/CourseListingButton.tsx
- src/client/components/pages/Schedule/blocks/SessionBlock.tsx
This adds `isFaded` and `isHighlighted` properties to the `SessionBlock` and `CourseListingButton` components that control the opacity setting of the element. When the user clicks on a single meeting, all other `SessionBlocks` that don't contain meetings in the same course will fade out. Within the blocks that do contain meetings in the same course, any other course numbers will be faded, while the chosen course will have a light highlight applied.
to change)
- [] Normal 
Fixes #505
> Fade course blocks that don't have popups

- src/client/components/pages/Schedule/SchedulePage.tsx
This PR updates the schedule such that the end time is extended from 8pm to 10pm. According to our users, the latest end time for a course is 9:30pm. For now, we will hardcode the end time value as 10pm, but we may dynamically update the end time in the future.
to change)
Fixes #535
> Fix Schedule Display - Extend end time to 10pm

- src/client/components/pages/Schedule/ScheduleView.tsx
- src/client/components/pages/Schedule/blocks/SessionBlock.tsx
This PR added an `isPopoverVisible` prop as an indication of whether a popover is currently showing. If the popover is showing, the scroll for that popover should be hidden. However, if a popover is showing, the faded blocks can still be scrolled. When no popover is showing, the schedule blocks should be scrollable like usual.
to change)
Fixes #549
> Improve scrolling for Popover elements in Schedule

- init-redis-ssl.sh
As of `bitnami/redis:6.2.7-debian-11-r18`, the startup script for redis
requires a file containing a passphrase to be provided via the
`REDIS_TLS_KEY_FILE_PASS` environment variable if Redis is running with
TLS enabled. Since we're only using this container in local development
and not in production, we can override by creating an empty file when we
initialize the SSL certificate so that it passes the "Does the file
exist?" check that the redis script is running.
to change)
Fixes #553
> Add an empty passphrase file

- src/client/api/index.ts
- src/client/components/pages/RoomSchedule/RoomSchedule.tsx
This is a continuation of PR https://github.com/seas-computing/course-planner/pull/557.
This was in response to the type error: `Unsafe call of an any typed value from @typescript-eslint/no-unsafe-call`. By exporting the rooms file from `index.ts`, we can import from `client/api` as opposed to `client/api/rooms`.
to change)
Fixes #550
> Update import and export statements for the Location API

- src/client/api/__tests__/location.test.ts
- src/client/api/rooms.ts
- src/client/components/layout/AppHeader.tsx
- src/client/components/layout/AppRouter.tsx
- src/client/components/layout/__tests__/AppHeader.test.tsx
- src/client/components/pages/RoomAdmin/RoomAdmin.tsx
- src/client/components/pages/RoomAdmin/__tests__/RoomAdminTable.test.tsx
- src/client/components/pages/index.ts
- src/common/__tests__/data/locations.ts
- src/common/dto/room/RoomAdminResponse.dto.ts
- src/server/location/location.controller.ts
- src/server/location/location.module.ts
- src/server/location/location.service.ts
- tests/integration/e2e/AppRouter.test.tsx
- tests/integration/server/location/location.controller.test.ts
This PR adds the initial Room Admin page, which includes the room admin table with campus, building, name, and capacity information. The functionality of the edit buttons will be implemented in a future ticket. 
to change)
Fixes #566
> Add Initial Room Admin Page & Table

- src/client/components/App.tsx
- src/client/components/__tests__/App.test.tsx
- src/common/__tests__/data/metadata.ts
- src/common/dto/metadata/MetadataResponse.dto.ts
- src/common/dto/room/CampusResponse.dto.ts
- src/server/location/__tests__/location.service.test.ts
- src/server/location/location.module.ts
- src/server/location/location.service.ts
- src/server/metadata/__tests__/metadata.controller.test.ts
- src/server/metadata/metadata.controller.ts
- src/server/metadata/metadata.module.ts
This PR updates the metadata to include campus information. The campus information outlines the buildings and rooms that are in that campus. This will be used to populate the campus and building dropdowns in the Create Room modal and can be used to check that users are not creating existing campuses, buildings, and rooms.
to change)
Fixes #572
> Add Campus Information to Metadata

- src/client/components/pages/Courses/MeetingModal.tsx
- tests/integration/e2e/CoursesPage.test.tsx
This PR adds client side validation that checks that meeting times without rooms for a course instance do not overlap. For instance, a user should not be able to save meetings (without rooms) that span from 12:00-1:00PM and 12:30-1:30PM. 
to change)
Fixes #403
> Validate Meeting Times without Rooms

- src/client/components/pages/Courses/tableFields.tsx
Originally, the placeholder text was created by using the `field` value, which tends to be in camel case. Instead, we would like the placeholder text to be in title case. Using the helper function, `camelCaseToTitleCase`, we can manipulate the `field` and `subfield`s to have the placeholder text show as expected. The reason why we are using the `subField` value is for properties nested under the `fall` and `spring` semesters. For now, we only have one text filter under the `fall` and `spring` semesters (`instructor` column), but we may want to add more text filters in the future. By incorporating the `subField` into the placeholder text, there is a differentiation between different properties nested under `fall` and `spring`.
to change)
Fixes #599
> Update Placeholder Text for Courses Table

- src/server/metadata/metadata.controller.ts
The `/metadata` endpoint does not return any sensitive data and is required for the world-readable pages on the info.seas site. So we do not need to block anonymous users.
to change)
Fixes #608
> Remove authentication from metadata endpoint

- src/client/components/pages/Courses/MeetingModal.tsx
This PR moves the loading spinner from the modal footer...
.... and into the modal body
this fixes a UI bug where saving meetings causes the modal footer (and buttons) to stretch vertically. It also hides the modal content when saving, which is how other modals behave, so it also provides some consistency.
to change)
Fixes #595
> Move loading spinner to modal body

- src/client/components/pages/Schedule/ScheduleView.tsx
When the prefix is not active, the cursor should be a regular arrow to show that the course cannot be clicked to reveal a popover with more info on the course.
to change)
Fixes #601
> Update logic determining the cursor style in the schedule

- src/client/api/__tests__/courses.test.ts
- src/client/components/pages/Courses/__tests__/CourseModal.test.tsx
- src/common/__tests__/data/courses.ts
- src/server/course/__tests__/course.controller.test.ts
- src/server/course/__tests__/course.service.test.ts
- src/server/course/course.service.ts
- src/server/courseInstance/courseInstance.service.ts
- tests/integration/server/course/course.controller.test.ts
- tests/integration/server/course/course.service.test.ts
- tests/integration/server/courseInstance/courseInstance.service.test.ts
This PR updates the ordering of courses so that instead of ordering by `catalogNumber`, we are ordering by the integer portion of the course number and the alpha part of the course number so that CS 50 appears before CS 100, for instance. 
to change)
Fixes #616
> Fix Course Ordering in Multi Year Plan and Course Admin tables

- .env-example
- docker-compose.yml
- package-lock.json
- package.json
- src/client/components/App.tsx
- webpackfile.client-dev.js
- webpackfile.js
This PR adds a `Footer` that contains the app version number via a (currently) hardcoded .env value. The `.env-example` file was updated to include the `APP_VERSION` variable. In the future, the version number will come from Github Actions as opposed to a hardcoded value. 
to change)
Fixes #618
> Add version tag via hardcoded .env variable

- .github/workflows/05-publish.yml
In order to get the version that is on Github Actions, we are updating the "publish" workflow to set the value of the APP_VERSION variable to be equal to the value of the Github Actions VERSION_TAG.
to change)
Fixes #618
> Set the app version using the version listed in Github Actions

- src/client/components/pages/Courses/RoomSelectionTable.tsx
- src/client/components/pages/Courses/__tests__/RoomSelectionTable.test.tsx
- src/common/__tests__/data/locations.ts
Any rooms not managed by SEAS were assumed to be FAS. However, given the possible usage of HBS, Longwood etc. rooms in the future....adding a special case for each campus would quickly become unmanagable. Add to that the fact that HBS is _technically_ in Allston.
Therefore, any non-seas rooms are now part of a ficticious "Non-SEAS" campus in the campus table rather than creating special cases for each Harvard school. This still allows the room to be booked, but under the proviso of "We don't have any availability for this room, so you should double check with room book"
to change)
Fixes #596
> Show "Check Availability" for all non-seas rooms

- src/client/components/pages/Schedule/ScheduleView.tsx
- src/server/courseInstance/MultiYearPlanView.entity.ts
- src/server/courseInstance/ScheduleBlockView.entity.ts
- src/server/courseInstance/ScheduleEntryView.entity.ts
- src/server/courseInstance/courseInstance.service.ts
- src/server/migrations/1677723792323-AddSameAsId.ts
- src/server/migrations/1678123233937-UpdateScheduleEntryView.ts
- src/server/migrations/1678202422266-UpdateScheduleEntryView.ts
- src/server/migrations/1678297871835-UpdateScheduleBlockView.ts
- tests/integration/e2e/MultiYearPlan.test.tsx
- tests/integration/e2e/SchedulePage.test.tsx
This PR contains 3 migrations. It updates the server logic such that the Multi Year Plan table will show the instructors of the course's parent if there is one. It also updates the Schedule such that the meeting information (day, time, and room information) of the parent, if there is one, is displayed.
A separate PR will be opened to update the display of the Faculty table to show the same as relationship. 
to change)
Fixes #642
> Incorporate Same As Logic to Update Multi Year Plan and Schedule Table Displays
